arch:
- aarch64
- amd64
codenotary: alexandrep.github@gmail.com
description: Open Source Online Genealogy System
devices:
- "/dev/dri"
- "/dev/dri/card0"
- "/dev/dri/card1"
- "/dev/dri/renderD128"
- "/dev/vchiq"
- "/dev/video10"
- "/dev/video11"
- "/dev/video12"
- "/dev/video13"
- "/dev/video14"
- "/dev/video15"
- "/dev/video16"
- "/dev/ttyUSB0"
- "/dev/sda"
- "/dev/sdb"
- "/dev/sdc"
- "/dev/sdd"
- "/dev/sde"
- "/dev/sdf"
- "/dev/sdg"
- "/dev/nvme"
- "/dev/nvme0n1p1"
- "/dev/nvme0n1p2"
- "/dev/nvme0n1p3"
- "/dev/nvme1n1p1"
- "/dev/nvme1n1p2"
- "/dev/nvme1n1p3"
- "/dev/nvme2n1p1"
- "/dev/nvme2n1p2"
- "/dev/nvme3n1p3"
- "/dev/mmcblk"
- "/dev/fuse"
- "/dev/sda1"
- "/dev/sdb1"
- "/dev/sdc1"
- "/dev/sdd1"
- "/dev/sde1"
- "/dev/sdf1"
- "/dev/sdg1"
- "/dev/sda2"
- "/dev/sdb2"
- "/dev/sdc2"
- "/dev/sdd2"
- "/dev/sde2"
- "/dev/sdf2"
- "/dev/sdg2"
- "/dev/sda3"
- "/dev/sdb3"
- "/dev/sda4"
- "/dev/sdb4"
- "/dev/sda5"
- "/dev/sda6"
- "/dev/sda7"
- "/dev/sda8"
- "/dev/nvme0"
- "/dev/nvme1"
- "/dev/nvme2"
environment: {
  "GRAMPSWEB_TREE": "Gramps Web",
  "GRAMPSWEB_CELERY_CONFIG__broker_url": "redis://localhost:6379/0",
  "GRAMPSWEB_CELERY_CONFIG__result_backend": "redis://localhost:6379/0",
  "GRAMPSWEB_RATELIMIT_STORAGE_URI": "redis://localhost:6379/1",
  "GRAMPS_API_CONFIG": "/config/config/config.cfg",
  "GRAMPSWEB_USER_DB_URI": "sqlite:////config/users/users.sqlite",
  "GRAMPSWEB_MEDIA_BASE_DIR": "/config/media",
  "GRAMPSWEB_SEARCH_INDEX_DB_URI": "sqlite:////config/indexdir/search_index.db",
  "GRAMPSWEB_STATIC_PATH": "/app/static",
  "GRAMPSWEB_THUMBNAIL_CACHE_CONFIG__CACHE_DIR": "/config/thumbnail_cache",
  "GRAMPSWEB_REPORT_DIR": "/config/cache/reports",
  "GRAMPSWEB_EXPORT_DIR": "/config/cache/export"
}
image: ghcr.io/alexbelgium/grampsweb-{arch}
init: false
options: {
 "certfile": "fullchain.pem",
 "keyfile": "privkey.pem"
}
map:
  - type: addon_config
    read_only: false
  - type: ssl
    read_only: true
name: "Grampsweb not working"
ports:
  5001/tcp: 5000
ports_description:
  5001/tcp: webui
schema: {
  "GRAMPSWEB_SECRET_KEY": "str?",
  "GRAMPSWEB_BASE_URL": "str?",
  "certfile": "str",
  "keyfile": "str",
  "ssl": "bool"
}
services:
- mysql:want
slug: grampsweb
tmpfs: true
url: https://github.com/alexbelgium/hassio-addons/tree/master/grampsweb
version: "1.6"
webui: "[PROTO:ssl]://[HOST]:[PORT:5001]"
