arch:
- aarch64
- amd64
codenotary: alexandrep.github@gmail.com
description: Open Source Online Genealogy System
devices:
- "/dev/dri"
- "/dev/dri/card0"
- "/dev/dri/card1"
- "/dev/dri/renderD128"
- "/dev/vchiq"
- "/dev/video10"
- "/dev/video11"
- "/dev/video12"
- "/dev/video13"
- "/dev/video14"
- "/dev/video15"
- "/dev/video16"
- "/dev/ttyUSB0"
- "/dev/sda"
- "/dev/sdb"
- "/dev/sdc"
- "/dev/sdd"
- "/dev/sde"
- "/dev/sdf"
- "/dev/sdg"
- "/dev/nvme"
- "/dev/nvme0n1p1"
- "/dev/nvme0n1p2"
- "/dev/nvme0n1p3"
- "/dev/nvme1n1p1"
- "/dev/nvme1n1p2"
- "/dev/nvme1n1p3"
- "/dev/nvme2n1p1"
- "/dev/nvme2n1p2"
- "/dev/nvme3n1p3"
- "/dev/mmcblk"
- "/dev/fuse"
- "/dev/sda1"
- "/dev/sdb1"
- "/dev/sdc1"
- "/dev/sdd1"
- "/dev/sde1"
- "/dev/sdf1"
- "/dev/sdg1"
- "/dev/sda2"
- "/dev/sdb2"
- "/dev/sdc2"
- "/dev/sdd2"
- "/dev/sde2"
- "/dev/sdf2"
- "/dev/sdg2"
- "/dev/sda3"
- "/dev/sdb3"
- "/dev/sda4"
- "/dev/sdb4"
- "/dev/sda5"
- "/dev/sda6"
- "/dev/sda7"
- "/dev/sda8"
- "/dev/nvme0"
- "/dev/nvme1"
- "/dev/nvme2"
environment: {
  "GRAMPSWEB_TREE": "Gramps Web",
  "GRAMPSWEB_CELERY_CONFIG__broker_url": "redis://localhost:6379/0",
  "GRAMPSWEB_CELERY_CONFIG__result_backend": "redis://localhost:6379/0",
  "GRAMPSWEB_RATELIMIT_STORAGE_URI": "redis://localhost:6379/1"
}
image: ghcr.io/alexbelgium/grampsweb-{arch}
init: false
map:
  - type: addon_config
    read_only: false
name: Grampsweb
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: webui
schema: {
  "GRAMPSWEB_SECRET_KEY": "str?"
}
services:
- mysql:want
slug: grampsweb
tmpfs: true
url: https://github.com/alexbelgium/hassio-addons/tree/master/grampsweb
version: "0.6"
webui: "[PROTO:ssl]://[HOST]:[PORT:5000]"
