arch:
  - aarch64
  - amd64
description: Open source password management solution
image: ghcr.io/alexbelgium/vaultwarden-{arch}
init: false
map:
  - ssl
name: Vaultwarden
options:
  env_vars: []
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: true
ports:
  7277/tcp: 7277
ports_description:
  7277/tcp: Bitwarden Vault
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  request_size_limit: int?
  ssl: bool
slug: bitwarden
udev: true
url: https://github.com/alexbelgium/hassio-addons/tree/master/bitwarden
version: 1.35.0-3
webui: "[PROTO:ssl]://[HOST]:[PORT:7277]"
