arch:
  - aarch64
  - amd64
description: Open source password management solution
image: ghcr.io/alexbelgium/vaultwarden-{arch}
init: false
map:
  - ssl
name: zzz_archived - Vaultwarden
options:
  env_vars: []
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
ports:
  7277/tcp: 7277
ports_description:
  7277/tcp: Vaultwarden Web interface
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  request_size_limit: int?
slug: bitwarden
stage: deprecated
udev: true
url: https://github.com/alexbelgium/hassio-addons/tree/master/bitwarden
version: 1.35.0
webui: "[PROTO:ssl]://[HOST]:[PORT:7277]"
