version: '3'
services:
  musicbrainz-picard:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - TAKE_CONFIG_OWNERSHIP=${TAKE_CONFIG_OWNERSHIP}
      - CLEAN_TMP_DIR=${CLEAN_TMP_DIR}
      - SECURE_CONNECTION=${SECURE_CONNECTION}
      - VNC_PASSWORD=${VNC_PASSWORD}
    volumes:
      - ${VOLUME_CONFIG}:/config
    ports:
      - '5800:5800'
      - '5900:5900'
