arch:
  - aarch64
  - amd64
codenotary: alexandrep.github@gmail.com
description: Display your immich gallery as a digital photo frame
hassio_api: true
image: ghcr.io/alexbelgium/immich_frame-{arch}
init: false
map:
  - addon_config:rw
name: Immich Frame
options:
  env_vars: []
ports:
  8080/tcp: 8171
ports_description:
  8080/tcp: Web UI port
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
  ApiKey: str
  ImmichServerUrl: str
  TZ: str?
slug: immich_frame
url: https://github.com/alexbelgium/hassio-addons
version: "1.0.29.0"
webui: http://[HOST]:[PORT:8080]
