arch:
  - aarch64
  - amd64
description: "\U0001F5A7\U0001F50D WIFI / LAN scanner, intruder, and presence detector"
environment:
  PGID: "20211"
  PORT: "20211"
  PUID: "20211"
  TZ: Europe/Berlin
  NETALERTX_DATA: /config
  NETALERTX_CONFIG: /config/config
  NETALERTX_DB: /config/db
  TMP_DIR: /tmp/tmp
hassio_api: true
host_network: true
image: ghcr.io/alexbelgium/netalertx-{arch}
ingress: true
ingress_port: 0
ingress_stream: true
init: false
map:
  - addon_config:rw
  - media:rw
  - share:rw
  - ssl
name: NetAlertX
options:
  env_vars: []
panel_icon: mdi:wifi-check
ports:
  20211/tcp: 20211
  20212/tcp: 20212
ports_description:
  20211/tcp: WebUI port
  20212/tcp: GraphQL port
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
  - NET_ADMIN
  - NET_RAW
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
  APP_CONF_OVERRIDE: str?
  TZ: str?
services:
  - mqtt:want
slug: netalertx
tmpfs: true
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: 25.11.29
