arch:
  - aarch64
  - amd64
  - armv7
codenotary: alexandrep.github@gmail.com
description: Deprecated - please use community version
image: ghcr.io/alexbelgium/vaultwarden-{arch}
init: false
map:
  - ssl
name: zzz_archived - Vaultwarden
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: true
  env_vars: []
ports:
  7277/tcp: 7277
ports_description:
  7277/tcp: Bitwarden Vault
schema:
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  request_size_limit: int?
  ssl: bool
  env_vars:
    - name: match(^[A-Z0-9_]+$)
      value: str
slug: bitwarden
stage: deprecated
udev: true
url: https://github.com/alexbelgium/hassio-addons/tree/master/bitwarden
version: 1.34.3
webui: '[PROTO:ssl]://[HOST]:[PORT:7277]'
