arch:
  - amd64
  - aarch64
backup_exclude:
  - "**/cache/**"
description: Navidrome for Home Assistant
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n3p3
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
image: ghcr.io/alexbelgium/navidrome-{arch}
init: false
map:
  - addon_config:rw
  - media
  - share:rw
  - ssl:rw
name: Navidrome
options:
  env_vars: []
  base_url: /
  certfile: fullchain.pem
  data_folder: /data
  keyfile: privkey.pem
  log_level: info
  music_folder: /data/music
  ssl: false
ports:
  4533/tcp: 4533
ports_description:
  4533/tcp: Web interface
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
  base_url: str
  certfile: str?
  cifsdomain: str?
  cifspassword: str?
  cifsusername: str?
  data_folder: str
  default_language: str?
  image_cache_size: str?
  keyfile: str?
  lastfm_api_key: str?
  lastfm_secret: str?
  localdisks: str?
  log_level: str
  music_folder: str
  networkdisks: str?
  password_encryption_key: str?
  scan_schedule: str?
  spotify_id: str?
  spotify_secret: str?
  ssl: bool
  transcoding_cache_size: str?
  welcome_message: str?
slug: navidrome
udev: true
url: https://github.com/alexbelgium/hassio-addons/tree/master/navidrome
version: 0.58.5-2
webui: "[PROTO:ssl]://[HOST]:[PORT:4533]"
