arch:
  - aarch64
  - amd64
description: "\U0001F426 NetBird self-hosted server stack (management, signal, dashboard, coturn)"
image: ghcr.io/alexbelgium/netbird-server-{arch}
init: false
ingress: false
map:
  - addon_config:rw
name: NetBird Server
options: {}
schema: {}
slug: netbird-server
ports:
  33073/tcp: 33073
  10000/tcp: 10000
  8080/tcp: 8080
  3478/udp: 3478
ports_description:
  33073/tcp: Management API (HTTP/gRPC)
  10000/tcp: Signal gRPC
  8080/tcp: NetBird Dashboard (HTTP)
  3478/udp: Coturn STUN/TURN
url: https://github.com/alexbelgium/hassio-addons
version: 0.64.5-1
