arch:
  - aarch64
  - amd64
audio: true
description: Brave browser
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
environment:
  FM_HOME: /config
  HOME: /config
  START_DOCKER: "false"
  TITLE: Brave browser
  shm_size: 1gb
image: ghcr.io/alexbelgium/brave-{arch}
ingress: true
init: false
map:
  - addon_config:rw
  - media:rw
  - share:rw
  - ssl
name: Brave
options:
  env_vars: []
  DNS_server: 8.8.8.8
  PGID: 0
  PUID: 0
  certfile: fullchain.pem
  keyfile: privkey.pem
  use_own_certs: false
panel_admin: false
panel_icon: mdi:monitor
ports:
  3001/tcp: 3001
  9221/tcp: null
ports_description:
  3001/tcp: Web interface https
  9221/tcp: Chrome devtools
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
  DNS_server: str?
  DRINODE: list(/dev/dri/card0|/dev/dri/card1|/dev/dri/card2|/dev/dri/renderD128|/dev/dri/renderD129|)?
  KEYBOARD: list(da-dk-qwerty|de-de-qwertz|en-gb-qwerty|en-us-qwerty|es-es-qwerty|fr-ch-qwertz|fr-fr-azerty|it-it-qwerty|ja-jp-qwerty|pt-br-qwerty|sv-se-qwerty|tr-tr-qwerty)?
  PASSWORD: str?
  PGID: int
  PUID: int
  TZ: match([A-Z][a-z]*./[A-Z][a-z]*.)?
  additional_apps: str?
  certfile: str
  keyfile: str
  use_own_certs: bool?
slug: brave
tmpfs: true
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: "1.86.139-ls69-7"
video: true
