arch:
  - aarch64
  - amd64
audio: true
description: Brave browser
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
environment:
  FM_HOME: /config
  HOME: /config
  START_DOCKER: "false"
  TITLE: Brave browser
  shm_size: 1gb
image: ghcr.io/alexbelgium/brave-{arch}
ingress: true
init: false
map:
  - addon_config:rw
  - media:rw
  - share:rw
  - ssl
name: Brave
options:
  env_vars: []
  PGID: 0
  PUID: 0
  certfile: fullchain.pem
  keyfile: privkey.pem
  use_own_certs: true
ports:
  20/tcp: null
  21/tcp: null
  22/tcp: null
  23/tcp: null
  25/tcp: null
  3000/tcp: null
  3001/tcp: null
  3002/tcp: null
  53/tcp: null
  80/tcp: null
ports_description:
  20/tcp: FTP
  21/tcp: FTP
  22/tcp: SSH
  23/tcp: TELNET
  25/tcp: SMTP
  3000/tcp: Web interface
  3001/tcp: Web interface https
  3002/tcp: custom port 2
  53/tcp: DNS
  80/tcp: http
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
  PGID: int
  PUID: int
  TZ: match([A-Z][a-z]*./[A-Z][a-z]*.)?
  certfile: str
  keyfile: str
  use_own_certs: bool?
slug: brave
tmpfs: true
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: "1.0.2"
video: true
