arch:
  - aarch64
  - amd64
  - armv7
description: M3U Proxy for Plex DVR and Emby Live TV
environment:
  XTEVE_CONF: /data/conf
  XTEVE_HOME: /data
host_network: true
image: ghcr.io/alexbelgium/xteve-{arch}
map:
  - config:rw
  - share:rw
  - ssl:ro
name: Xteve
options:
  env_vars: []
ports:
  34400/tcp: 34400
ports_description:
  34400/tcp: Web interface
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
slug: xteve
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: 2.5.3-4
webui: "[PROTO:ssl]://[HOST]:[PORT:34400]/web"
