arch:
  - amd64
  - aarch64
description: manage your personal workouts, weight and diet plans
image: ghcr.io/alexbelgium/wger-{arch}
map:
  - addon_config:rw
  - homeassistant_config:rw
  - share:rw
  - ssl:ro
name: Wger
options:
  env_vars: []
  CONFIG_LOCATION: /config/config.yaml
ports:
  80/tcp: 9927
ports_description:
  80/tcp: Web interface
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
  CONFIG_LOCATION: str
slug: wger
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: 2.4-12
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
