arch:
  - aarch64
  - amd64
description: web page monitoring, notification and change detection
environment:
  LC_ALL: en_US.UTF-8
  TIMEOUT: "60000"
image: ghcr.io/alexbelgium/changedetection.io-{arch}
ingress: true
init: false
map:
  - config:rw
name: Changedetection.io
panel_icon: mdi:vector-difference
options:
  env_vars: []
  PGID: 0
  PUID: 0
  TIMEOUT: "60000"
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Webui (not required for Ingress)
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
  BASE_URL: str?
  PGID: int
  PLAYWRIGHT_DRIVER_URL: str?
  PUID: int
  TIMEOUT: int
  TZ: str?
slug: changedetection.io
udev: true
url: https://github.com/alexbelgium/hassio-addons/tree/master/changedetection.io
version: "0.52.4-3"
webui: http://[HOST]:[PORT:5000]
