arch:
  - aarch64
  - amd64
name: Karakeep
slug: karakeep
description: A self-hostable bookmark-everything app (links, notes and images) with AI-based automatic tagging and full text search
version: "0.30.0"
url: https://github.com/alexbelgium/hassio-addons/tree/master/karakeep
image: ghcr.io/alexbelgium/karakeep-{arch}
init: false
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Web UI
webui: "[PROTO:ssl]://[HOST]:[PORT:3000]"
map:
  - addon_config:rw
  - share:rw
environment:
  DATA_DIR: /data
  XDG_CACHE_HOME: /data/cache
  BROWSER_WEB_URL: http://127.0.0.1:9222
  CHROME_EXTENSIONS_DIR: /usr/src/chrome/extensions
  MEILI_ADDR: http://127.0.0.1:7700
  MEILI_NO_ANALYTICS: "true"
  DISABLE_NEW_RELEASE_CHECK: "true"
options:
  TZ: Etc/UTC
  DISABLE_SIGNUPS: false
  NEXTAUTH_SECRET: ""
  NEXTAUTH_URL: ""
  MAX_ASSET_SIZE_MB: 4
  OPENAI_API_KEY: ""
  OCR_LANGS: ""
  INFERENCE_LANG: ""
  CRAWLER_DOWNLOAD_BANNER_IMAGE: true
  CRAWLER_STORE_SCREENSHOT: true
  CRAWLER_FULL_PAGE_SCREENSHOT: true
  CRAWLER_FULL_PAGE_ARCHIVE: true
  CRAWLER_ENABLE_ADBLOCKER: true
  CRAWLER_VIDEO_DOWNLOAD: false
schema:
  TZ: str?
  DISABLE_SIGNUPS: bool
  NEXTAUTH_SECRET: password?
  NEXTAUTH_URL: str?
  MAX_ASSET_SIZE_MB: int?
  OPENAI_API_KEY: password?
  OCR_LANGS: str?
  INFERENCE_LANG: str?
  MEILI_MASTER_KEY: str?
  CRAWLER_DOWNLOAD_BANNER_IMAGE: bool
  CRAWLER_STORE_SCREENSHOT: bool
  CRAWLER_FULL_PAGE_SCREENSHOT: bool
  CRAWLER_FULL_PAGE_ARCHIVE: bool
  CRAWLER_ENABLE_ADBLOCKER: bool
  CRAWLER_VIDEO_DOWNLOAD: bool?
