name: BirdNET-PiPy
slug: birdnet-pipy
description: BirdNET-PiPy bird detection with a modern web dashboard
version: 0.1.0
url: https://github.com/alexbelgium/hassio-addons/tree/master/birdnet-pipy
arch:
  - aarch64
  - amd64
ingress: true
ingress_stream: true
panel_icon: mdi:bird
init: false
map:
  - addon_config:rw
  - data:rw
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web UI
options:
  TZ: Etc/UTC
  ICECAST_PASSWORD: ""
  STREAM_BITRATE: 320k
  RECORDING_MODE: "rtsp"
  RTSP_URL: ""
  data_location: /config/data
  env_vars: []
schema:
  TZ: str?
  ICECAST_PASSWORD: str?
  STREAM_BITRATE: str?
  RECORDING_MODE: list(pulseaudio|http_stream|rtsp)
  RTSP_URL: str?
  data_location: str
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
audio: true
image: ghcr.io/alexbelgium/birdnet-pipy-{arch}
