arch:
  - aarch64
  - amd64
backup_exclude:
  - backups
description: An agent used to manage all the resources in a Swarm cluster
docker_api: true
full_access: true
hassio_api: true
image: ghcr.io/alexbelgium/portainer_agent-{arch}
init: false
map:
  - config:rw
  - share:rw
  - ssl
name: Portainer Agent
options:
  env_vars: []
ports:
  80/tcp: null
  9001/tcp: 9001
ports_description:
  80/tcp: Portainer edge agent
  9001/tcp: Portainer agent
schema:
  env_vars:
    - name: match(^[A-Za-z0-9_]+$)
      value: str?
  AGENT_CLUSTER_ADDR: str?
  AGENT_CLUSTER_PROBE_INTERVAL: str?
  AGENT_CLUSTER_PROBE_TIMEOUT: str?
  AGENT_SECRET: str?
  AGENT_SECRET_TIMEOUT: str?
  EDGE: list(0|1)?
  EDGE_ID: str?
  EDGE_INACTIVITY_TIMEOUT: str?
  EDGE_INSECURE_POLL: list(0|1)?
  EDGE_KEY: str?
  LOG_LEVEL: str?
  PORTAINER_AGENT_ARGS: str?
slug: portainer_agent
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: 2025.12-6
