name: Lint / Syntax checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    container: ghcr.io/hadolint/hadolint:latest-alpine
    steps:
      - name: â†©ï¸ Checkout
        uses: actions/checkout@v2
        
      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: ğŸ” Run hadolint
        run: |
          for files in ${{ steps.changed_files.outputs.all }}; do
            if [[ "$(basename ${files})" == "Dockerfile" ]]; then
              echo "Hadolint ${{ steps.changed_files.outputs.all }}"
              hadolint "${{ steps.changed_files.outputs.all }}"
            fi
          done

  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine@latest
    steps:
      - name: â†©ï¸ Checkout
        uses: actions/checkout@v2
        
      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: ğŸ” Run ShellCheck
        run: |
          for files in ${{ steps.changed_files.outputs.all }}; do
            if [[ "$(basename ${files})" == *".sh* ]]; then
              echo "Spellcheck ${{ steps.changed_files.outputs.all }}"
              hadolint "${{ steps.changed_files.outputs.all }}"
            fi
          done


  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: â†©ï¸ Checkout
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: ğŸ” Run markdownlint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          config_file: .markdownlint.yaml
