name: Weekly bash beautify

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
      
jobs:
  beautify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v3
      - name: "Install beautify"
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            beautysh
      - name: "Run beautify"
        run: |
          find . -name '*.sh' -print0 | xargs -0 beautysh --indent-size 4
      - name: Create New Pull Request If Needed
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Apply beautysh changes"
          branch-suffix: timestamp
          commit-message: Beautify bash
