name: "Manyfold"
slug: manyfold
description: "Manyfold 3D model manager as a Home Assistant add-on, using the upstream image with configurable library/index paths."
version: "1.0.3"
url: "https://github.com/alexbelgium/hassio-addons/tree/master/manyfold"
image: ghcr.io/alexbelgium/manyfold-{arch}
arch:
  - amd64
  - aarch64
startup: services
init: false

ports:
  3214/tcp: 3214
ports_description:
  3214/tcp: "Manyfold Web UI"

webui: "http://[HOST]:[PORT:3214]"

map:
  - addon_config:rw
  - share:rw
  - media:rw

options:
  secret_key_base: ""
  puid: 1000
  pgid: 1000
  multiuser: true
  library_path: "/share/manyfold/models"
  thumbnails_path: "/config/thumbnails"
  log_level: "info"
  web_concurrency: 4
  rails_max_threads: 16
  default_worker_concurrency: 4
  performance_worker_concurrency: 1
  max_file_upload_size: 1073741824
  max_file_extract_size: 1073741824

schema:
  secret_key_base: str
  puid: int
  pgid: int
  multiuser: bool
  library_path: str
  thumbnails_path: str
  log_level: list(info|debug|warn|error)
  web_concurrency: int
  rails_max_threads: int
  default_worker_concurrency: int
  performance_worker_concurrency: int
  max_file_upload_size: int
  max_file_extract_size: int
